server.port=8088
spring.application.name=balance_hidrico

# CONFIGURACIÓN DE SWAGGER / OPENAPI (SPRING BOOT 4)
springdoc.api-docs.path=/doc/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ===================================
# PostgreSQL + Hibernate (JPA) - NeonTech
# ===================================

spring.datasource.url=jdbc:postgresql://ep-plain-rain-a8wzncnl-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8GepZKhm5FjL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.packages-to-scan=cl.LaEsperanza.balance_hidrico.controller